M48
; DRILL file {KiCad 9.0.6} date 2026-01-11T15:28:49-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-11T15:28:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.400
%
G90
G05
T1
X147.11Y-90.75
X152.89Y-90.75
T2
X144.5Y-100.0
X155.5Y-100.0
T3
X150.0Y-100.0
M30
